language: rust
dist: trusty
cache: cargo
script: skip
os: linux
jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
    - if: branch != master
  include:
    - stage: test
      rust: stable
      script: ./ci/test.sh
    - rust: beta
      script: ./ci/test.sh
    - rust: nightly
      script: ./ci/test.sh 

    - stage: deploy
      services:
      - docker
      before_install:
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      script: ./ci/deploy.sh
      if: branch = master
