language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - docker

jobs:
  include:
    - stage: build
      script: ./ci/build.sh
    - stage: deploy
      script: ./ci/deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
    rust: stable