language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - docker

jobs:
  include:
    - stage: build
      script:
        - chmod ugo+w $(pwd)
        - docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder cargo build --release
        - docker build -t rusty .
        - docker tag rusty epequeno/rusty
    - stage: deploy
      if: $TRAVIS_RUST_VERSION = stable
      script:
        - docker login -u epequeno -p $DOCKER_PASSWORD
        - docker push epequeno/rusty
        - sudo chmod -R ugo+w $(pwd)/target
        - cargo publish --token $CRATESIO_API_KEY        

