language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - docker

before_install:
  - docker login -u epequeno -p $DOCKER_PASSWORD

script:
  - sudo chmod -R ugo+w $(pwd)
  - docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder cargo build --release
  - docker build -t rusty .
  - docker tag rusty epequeno/rusty

deploy:
  skip_cleanup: true
  provider: script
  script:
    - sudo chmod -R ugo+w $(pwd)/target
    - docker push epequeno/rusty
    - cargo publish --token $CRATESIO_API_KEY
  on:
    rust: stable