language: rust
before_script:
  - rustup component add clippy
  - cargo install --force cargo-audit
  - cargo install --force --git https://github.com/kbknapp/cargo-outdated
script:
  - cargo clippy
  - cargo audit
  - cargo outdated
cache: cargo
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

services:
  - docker

jobs:
  include:
    - stage: build
      script: ./ci/build.sh
#     - stage: deploy
#       script: ./ci/deploy.sh
#       if: (branch = master)