language: rust
dist: trusty
cache: cargo
script: skip
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
jobs:
  include:
    - stage: test
      rust: stable
      script: ./ci/test.sh
      if: branch != master
    - stage: test
      rust: beta
      script: ./ci/test.sh
      if: branch != master
    - stage: test
      rust: nightly
      script: ./ci/test.sh
      if: branch != master

    - stage: deploy
      services:
      - docker
      before_install:
      - pip install --user awscli
      - export PATH=$PATH:$HOME/.local/bin
      script: ./ci/deploy.sh
      if: branch = master