version: 0.2
env:
  parameter-store:
    DOCKER_PASSWORD: "DOCKER_PASSWORD"
phases:
  pre_build:
    commands:
      - docker login -u epequeno -p $DOCKER_PASSWORD
  build:
    commands:
      - git clone https://github.com/epequeno/rusty.git && cd rusty
      - chmod -R ugo+w ./rusty 
      - docker run --rm -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder cargo build --release
      - docker build -t rusty .
      - docker tag rusty epequeno/rusty
      - docker push epequeno/rusty