[package]
name = "rusty-slackbot"
version = "0.2.5"
authors = ["Steven Pequeno <steven@pequeno.in>"]
description = "a slack bot for sanantoniodevs.slack.com"
license = "GPL-3.0-or-later"
repository = "https://github.com/epequeno/rusty"
readme = "README.md"
keywords = ["bot", "slack", "rss"]
categories = ["web-programming"]

[dependencies]
slack = "0.22"
openssl-probe = "0.1.2"

[dependencies.rss]
version = "1"
features = ["from_url"]
