[package]
name = "rusty"
version = "0.1.0"
authors = ["Steven Pequeno <steven@pequeno.in>"]

[dependencies]
slack = "0.22"
openssl-probe = "0.1.2"

[dependencies.rss]
version = "*"
features = ["from_url"]