[package]
name = "rusty-slackbot"
version = "0.3.0"
authors = ["Steven Pequeno <steven@pequeno.in>"]
description = "a slack bot for sanantoniodevs.slack.com"
license = "GPL-3.0-or-later"
repository = "https://github.com/epequeno/rusty"
readme = "README.md"
keywords = ["bot", "slack", "rss"]
categories = ["web-programming"]
edition = "2018"

[dependencies]
slack = "0.22"
openssl-probe = "0.1.2"
env_logger = "0.6.0"
log = "0.4.6"
linked_hash_set = "0.1.3"
# https://github.com/rust-syndication/atom

[dependencies.rss]
version = "1"
features = ["from_url"]